//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAliFinancialService.AliService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AliService.IAli")]
    public interface IAli {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAli/GetJsonCurrentRate", ReplyAction="http://tempuri.org/IAli/GetJsonCurrentRateResponse")]
        string GetJsonCurrentRate();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAliChannel : TestAliFinancialService.AliService.IAli, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AliClient : System.ServiceModel.ClientBase<TestAliFinancialService.AliService.IAli>, TestAliFinancialService.AliService.IAli {
        
        public AliClient() {
        }
        
        public AliClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AliClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AliClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AliClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetJsonCurrentRate() {
            return base.Channel.GetJsonCurrentRate();
        }
    }
}
